<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAGjU4jw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAGjU4jw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAGjU4jw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAGjU4jw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAGjU4jw\App_KernelDevDebugContainer([
    'container.build_hash' => 'AGjU4jw',
    'container.build_id' => '1620b97b',
    'container.build_time' => 1627007553,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAGjU4jw');
